/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class curl_ssl_CurlLib */

#ifndef _Included_curl_ssl_CurlLib
#define _Included_curl_ssl_CurlLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     curl_ssl_CurlLib
 * Method:    init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_curl_ssl_CurlLib_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     curl_ssl_CurlLib
 * Method:    testUrl
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_curl_ssl_CurlLib_testUrl
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
